"""Initial Migration

Revision ID: eefc6358e961
Revises: 
Create Date: 2021-08-26 17:20:03.069012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eefc6358e961"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "experiment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "experiment_node",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("experiment_id", sa.Integer(), nullable=False),
        sa.Column("module_name", sa.String(length=255), nullable=False),
        sa.Column("input_from", sa.String(length=255), nullable=False),
        sa.Column("report_file_path", sa.String(length=255), nullable=True),
        sa.Column("output_file_path", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "experiment_id", "module_name", name="unique_module_for_experiment"
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("experiment_node")
    op.drop_table("user")
    op.drop_table("experiment")
    # ### end Alembic commands ###
